-- AlterTable
ALTER TABLE "CreditNote" ALTER COLUMN "amount" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Indemnisation" ALTER COLUMN "avans" SET DATA TYPE BIGINT,
ALTER COLUMN "rest" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "InternationalExpense" ALTER COLUMN "amount" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Invoice" ALTER COLUMN "amount" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "NationalExpense" ALTER COLUMN "amount" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "value" SET DATA TYPE BIGINT,
ALTER COLUMN "total" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "totalRon" SET DATA TYPE BIGINT,
ALTER COLUMN "totalEur" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "TripExpense" ALTER COLUMN "amount" SET DATA TYPE BIGINT,
ALTER COLUMN "amountEur" SET DATA TYPE BIGINT;
